default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: cable_dev

test:
  <<: *default
  database: cable_test

production:
  <<: *default
  database: cable_prod
