development:
  # Register in sandbox veritrans and get your keys here:
  # https://dashboard.sandbox.midtrans.com/settings/config_info
  client_key: ""
  server_key: ""
  api_host: https://api.sandbox.midtrans.com

production:
  # Register and get your keys here:
  # https://dashboard.midtrans.com/settings/config_info
  client_key: ""
  server_key: ""
  api_host: https://api.midtrans.com
