development:
  merchant_id: "test_id"
  merchant_hash_key: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789012345678901"
  finish_payment_return_url: "http://localhost/finish"
  unfinish_payment_return_url: "http://localhost/cancel"
  error_payment_return_url: "http://localhost/error"
  # server_host: "http://192.168.10.250:80"

production:
  merchant_id: "production_id"
  merchant_hash_key: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789012345678901"
  finish_payment_return_url: "http://mydomain/finish"
  unfinish_payment_return_url: "http://mydomain/cancel"
  error_payment_return_url: "http://mydomain/error"
  # server_host: "http://192.168.10.250:80"
