development:
  merchant_id: "test_id"
  merchant_hash_key: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789012345678901"
  finish_payment_return_url: "http://localhost/finish"
  unfinish_payment_return_url: "http://localhost/cancel"
  error_payment_return_url: "http://localhost/error"
  server_key: "c0b44171-d7fe-4cf5-8b15-06049fc9980c"
  # server_key: "2a8f3674-71cf-42af-aa56-b872b8924f72"
  server_host: "http://veritrans.dev"
  charges_url: "/charges"
  token_url:   "/tokens"

production:
  merchant_id: "production_id"
  merchant_hash_key: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789012345678901"
  finish_payment_return_url: "http://mydomain/finish"
  unfinish_payment_return_url: "http://mydomain/cancel"
  error_payment_return_url: "http://mydomain/error"
  server_key: "c0b44171-d7fe-4cf5-8b15-06049fc9980c"
  # server_key: "2a8f3674-71cf-42af-aa56-b872b8924f72"
  server_host: "http://veritrans.dev"
  charges_url: "/charges"
  token_url:   "/tokens"
  # server_host: "http://192.168.10.250:80"
